name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: Eli2694-Playground/backend@1
        with:
          owner: Eli2694
          repo: backend
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: testInvokation.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
