name: test2

on:
  workflow_dispatch:  # Triggered manually via dispatch event

jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s  # Simulates a build process (replace with actual build commands)
      - name: Test  # Needs the previous build job to finish
        uses: Eli2694-Playground/backend/.github/workflows/test2.yml@main
