name: test2
on:
  workflow_dispatch:
 
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
          
  test: 
    needs: build
    name: Test
    uses: Eli2694-Playground/backend/.github/workflows/test2.yml@main
     
